apiVersion: v1
kind: Pod
metadata:
  name: registry-test
  namespace: registry
spec:
  containers:
  - name: alpine
    image: alpine
    command: [ 'sh', '-c', 'apk add --no-cache curl && curl -v http://registry.test/v2/' ]
